/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMerkleVestingContract } from "./IMerkleVestingContract";
export type { VTVLMerkleVestingFactory } from "./VTVLMerkleVestingFactory";
