/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as vtvlMerkleVestingSol from "./VTVLMerkleVesting.sol";
export type { vtvlMerkleVestingSol };
export type { Verifier } from "./Verifier";
