/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export type MilestoneStruct = {
  startTime: BigNumberish;
  withdrawnAmount: BigNumberish;
  period: BigNumberish;
  releaseIntervalSecs: BigNumberish;
  isWithdrawn: boolean;
  allocation: BigNumberish;
  percent: BigNumberish;
};

export type MilestoneStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  boolean,
  BigNumber,
  number
] & {
  startTime: BigNumber;
  withdrawnAmount: BigNumber;
  period: BigNumber;
  releaseIntervalSecs: BigNumber;
  isWithdrawn: boolean;
  allocation: BigNumber;
  percent: number;
};

export interface SimpleMilestoneInterface extends utils.Interface {
  functions: {
    "allocation()": FunctionFragment;
    "claimableAmount(address,uint256)": FunctionFragment;
    "deposit(uint256)": FunctionFragment;
    "getAllRecipients()": FunctionFragment;
    "getMilestone(address,uint256)": FunctionFragment;
    "isAdmin(address)": FunctionFragment;
    "isCompleted(address,uint256)": FunctionFragment;
    "numTokensReservedForVesting()": FunctionFragment;
    "recipients(uint256)": FunctionFragment;
    "setAdmin(address,bool)": FunctionFragment;
    "setComplete(address,uint256)": FunctionFragment;
    "tokenAddress()": FunctionFragment;
    "withdraw(uint256)": FunctionFragment;
    "withdrawAdmin()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "allocation"
      | "claimableAmount"
      | "deposit"
      | "getAllRecipients"
      | "getMilestone"
      | "isAdmin"
      | "isCompleted"
      | "numTokensReservedForVesting"
      | "recipients"
      | "setAdmin"
      | "setComplete"
      | "tokenAddress"
      | "withdraw"
      | "withdrawAdmin"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "allocation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimableAmount",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllRecipients",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMilestone",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "isAdmin", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isCompleted",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "numTokensReservedForVesting",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recipients",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAdmin",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setComplete",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAdmin",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "allocation", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimableAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllRecipients",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isCompleted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numTokensReservedForVesting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "recipients", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setComplete",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAdmin",
    data: BytesLike
  ): Result;

  events: {
    "AdminAccessSet(address,bool)": EventFragment;
    "AdminWithdrawn(address,uint256)": EventFragment;
    "Claimed(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminAccessSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AdminWithdrawn"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Claimed"): EventFragment;
}

export interface AdminAccessSetEventObject {
  _admin: string;
  _enabled: boolean;
}
export type AdminAccessSetEvent = TypedEvent<
  [string, boolean],
  AdminAccessSetEventObject
>;

export type AdminAccessSetEventFilter = TypedEventFilter<AdminAccessSetEvent>;

export interface AdminWithdrawnEventObject {
  _recipient: string;
  _amountRequested: BigNumber;
}
export type AdminWithdrawnEvent = TypedEvent<
  [string, BigNumber],
  AdminWithdrawnEventObject
>;

export type AdminWithdrawnEventFilter = TypedEventFilter<AdminWithdrawnEvent>;

export interface ClaimedEventObject {
  _recipient: string;
  _withdrawalAmount: BigNumber;
}
export type ClaimedEvent = TypedEvent<[string, BigNumber], ClaimedEventObject>;

export type ClaimedEventFilter = TypedEventFilter<ClaimedEvent>;

export interface SimpleMilestone extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SimpleMilestoneInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    allocation(overrides?: CallOverrides): Promise<[BigNumber]>;

    claimableAmount(
      _recipient: string,
      _milestoneIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    deposit(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getAllRecipients(overrides?: CallOverrides): Promise<[string[]]>;

    getMilestone(
      _recipient: string,
      _milestoneIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[MilestoneStructOutput]>;

    isAdmin(
      _addressToCheck: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isCompleted(
      _recipient: string,
      _milestoneIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    numTokensReservedForVesting(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    recipients(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    setAdmin(
      admin: string,
      isEnabled: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setComplete(
      _recipient: string,
      _milestoneIndex: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    tokenAddress(overrides?: CallOverrides): Promise<[string]>;

    withdraw(
      _milestoneIndex: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    withdrawAdmin(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  allocation(overrides?: CallOverrides): Promise<BigNumber>;

  claimableAmount(
    _recipient: string,
    _milestoneIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  deposit(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getAllRecipients(overrides?: CallOverrides): Promise<string[]>;

  getMilestone(
    _recipient: string,
    _milestoneIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<MilestoneStructOutput>;

  isAdmin(_addressToCheck: string, overrides?: CallOverrides): Promise<boolean>;

  isCompleted(
    _recipient: string,
    _milestoneIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  numTokensReservedForVesting(overrides?: CallOverrides): Promise<BigNumber>;

  recipients(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  setAdmin(
    admin: string,
    isEnabled: boolean,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setComplete(
    _recipient: string,
    _milestoneIndex: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  tokenAddress(overrides?: CallOverrides): Promise<string>;

  withdraw(
    _milestoneIndex: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  withdrawAdmin(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    allocation(overrides?: CallOverrides): Promise<BigNumber>;

    claimableAmount(
      _recipient: string,
      _milestoneIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deposit(amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    getAllRecipients(overrides?: CallOverrides): Promise<string[]>;

    getMilestone(
      _recipient: string,
      _milestoneIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<MilestoneStructOutput>;

    isAdmin(
      _addressToCheck: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isCompleted(
      _recipient: string,
      _milestoneIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    numTokensReservedForVesting(overrides?: CallOverrides): Promise<BigNumber>;

    recipients(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    setAdmin(
      admin: string,
      isEnabled: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setComplete(
      _recipient: string,
      _milestoneIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    tokenAddress(overrides?: CallOverrides): Promise<string>;

    withdraw(
      _milestoneIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawAdmin(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "AdminAccessSet(address,bool)"(
      _admin?: string | null,
      _enabled?: null
    ): AdminAccessSetEventFilter;
    AdminAccessSet(
      _admin?: string | null,
      _enabled?: null
    ): AdminAccessSetEventFilter;

    "AdminWithdrawn(address,uint256)"(
      _recipient?: string | null,
      _amountRequested?: null
    ): AdminWithdrawnEventFilter;
    AdminWithdrawn(
      _recipient?: string | null,
      _amountRequested?: null
    ): AdminWithdrawnEventFilter;

    "Claimed(address,uint256)"(
      _recipient?: string | null,
      _withdrawalAmount?: null
    ): ClaimedEventFilter;
    Claimed(
      _recipient?: string | null,
      _withdrawalAmount?: null
    ): ClaimedEventFilter;
  };

  estimateGas: {
    allocation(overrides?: CallOverrides): Promise<BigNumber>;

    claimableAmount(
      _recipient: string,
      _milestoneIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deposit(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getAllRecipients(overrides?: CallOverrides): Promise<BigNumber>;

    getMilestone(
      _recipient: string,
      _milestoneIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isAdmin(
      _addressToCheck: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isCompleted(
      _recipient: string,
      _milestoneIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    numTokensReservedForVesting(overrides?: CallOverrides): Promise<BigNumber>;

    recipients(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setAdmin(
      admin: string,
      isEnabled: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setComplete(
      _recipient: string,
      _milestoneIndex: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    tokenAddress(overrides?: CallOverrides): Promise<BigNumber>;

    withdraw(
      _milestoneIndex: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    withdrawAdmin(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    allocation(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    claimableAmount(
      _recipient: string,
      _milestoneIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deposit(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getAllRecipients(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getMilestone(
      _recipient: string,
      _milestoneIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isAdmin(
      _addressToCheck: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isCompleted(
      _recipient: string,
      _milestoneIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    numTokensReservedForVesting(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    recipients(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setAdmin(
      admin: string,
      isEnabled: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setComplete(
      _recipient: string,
      _milestoneIndex: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    tokenAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdraw(
      _milestoneIndex: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    withdrawAdmin(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
