/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC20Extented__factory } from "./IERC20Extented__factory";
export { UniswapOracle__factory } from "./UniswapOracle__factory";
