/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Ownable } from "./Ownable";
export type { ERC20 } from "./ERC20";
export type { IERC20Metadata } from "./IERC20Metadata";
export type { IERC20 } from "./IERC20";
export type { AccessProtected } from "./AccessProtected";
export type { TestERC20Token } from "./TestERC20Token";
export type { FullPremintERC20Token } from "./FullPremintERC20Token";
export type { VariableSupplyERC20Token } from "./VariableSupplyERC20Token";
export type { VTVLVesting } from "./VTVLVesting";

export { Ownable__factory } from "./factories/Ownable__factory";
export { ERC20__factory } from "./factories/ERC20__factory";
export { IERC20Metadata__factory } from "./factories/IERC20Metadata__factory";
export { IERC20__factory } from "./factories/IERC20__factory";
export { AccessProtected__factory } from "./factories/AccessProtected__factory";
export { TestERC20Token__factory } from "./factories/TestERC20Token__factory";
export { FullPremintERC20Token__factory } from "./factories/FullPremintERC20Token__factory";
export { VariableSupplyERC20Token__factory } from "./factories/VariableSupplyERC20Token__factory";
export { VTVLVesting__factory } from "./factories/VTVLVesting__factory";
