/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FullPremintERC20Token } from "./FullPremintERC20Token";
export type { VariableSupplyERC20Token } from "./VariableSupplyERC20Token";
