/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IVestingFee,
  IVestingFeeInterface,
} from "../../contracts/IVestingFee";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_feePercent",
        type: "uint256",
      },
    ],
    name: "setFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_newReceiver",
        type: "address",
      },
    ],
    name: "updateFeeReceiver",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_minPrice",
        type: "uint256",
      },
    ],
    name: "updateMinWithdrawPrice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IVestingFee__factory {
  static readonly abi = _abi;
  static createInterface(): IVestingFeeInterface {
    return new utils.Interface(_abi) as IVestingFeeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVestingFee {
    return new Contract(address, _abi, signerOrProvider) as IVestingFee;
  }
}
