/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20Extented } from "./IERC20Extented";
export type { UniswapOracle } from "./UniswapOracle";
