/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Permit",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Permit__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20Permit",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Permit__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "AccessProtected",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccessProtected__factory>;
    getContractFactory(
      name: "FeeControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FeeControl__factory>;
    getContractFactory(
      name: "IVestingFee",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVestingFee__factory>;
    getContractFactory(
      name: "TestERC20Token",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TestERC20Token__factory>;
    getContractFactory(
      name: "FullPremintERC20Token",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FullPremintERC20Token__factory>;
    getContractFactory(
      name: "VariableSupplyERC20Token",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VariableSupplyERC20Token__factory>;
    getContractFactory(
      name: "VTVLVesting",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VTVLVesting__factory>;
    getContractFactory(
      name: "VTVLVestingFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VTVLVestingFactory__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Permit",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Permit>;
    getContractAt(
      name: "IERC20Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20Permit",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Permit>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "AccessProtected",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AccessProtected>;
    getContractAt(
      name: "FeeControl",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FeeControl>;
    getContractAt(
      name: "IVestingFee",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IVestingFee>;
    getContractAt(
      name: "TestERC20Token",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TestERC20Token>;
    getContractAt(
      name: "FullPremintERC20Token",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FullPremintERC20Token>;
    getContractAt(
      name: "VariableSupplyERC20Token",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.VariableSupplyERC20Token>;
    getContractAt(
      name: "VTVLVesting",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.VTVLVesting>;
    getContractAt(
      name: "VTVLVestingFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.VTVLVestingFactory>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
