/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FullPremintERC20Token__factory } from "./FullPremintERC20Token__factory";
export { VariableSupplyERC20Token__factory } from "./VariableSupplyERC20Token__factory";
